'use client';

import { useEffect, useState } from 'react';
import platformFinanceService, { FinanceBootstrap, PlatformExpenseRow, WalletTransferReview } from '@/services/platform-finance-service';

const money = (value: number) => `${new Intl.NumberFormat('ar-EG', { minimumFractionDigits: 2 }).format(value)} ج.م`;

export default function ExpenseManager() {
  const [rows, setRows] = useState<PlatformExpenseRow[]>([]);
  const [reviews, setReviews] = useState<WalletTransferReview[]>([]);
  const [bootstrap, setBootstrap] = useState<FinanceBootstrap | null>(null);
  const [editing, setEditing] = useState<string | null>(null);
  const [beneficiary, setBeneficiary] = useState('');
  const [reason, setReason] = useState('');
  const [categoryId, setCategoryId] = useState('');
  const [destinationTreasuryId, setDestinationTreasuryId] = useState('');
  const [error, setError] = useState('');
  const load = async () => { try { const [expenses, pendingReviews, financeBootstrap] = await Promise.all([platformFinanceService.getExpenses(), platformFinanceService.getWalletTransferReviews(), platformFinanceService.bootstrap()]); setRows(expenses); setReviews(pendingReviews); setBootstrap(financeBootstrap); } catch { setError('تعذر تحميل المصروفات أو تحويلات المحافظ'); } };
  useEffect(() => { void load(); }, []);
  async function reverse(id: string) { const reason = window.prompt('سبب عكس المصروف؟'); if (!reason) return; try { await platformFinanceService.reverseExpense(id, reason); await load(); } catch { setError('تعذر عكس المصروف'); } }
  async function backfill() { try { const result = await platformFinanceService.backfillWalletTransferReviews(); await load(); if (result.added === 0) setError('لا توجد رسائل تحويل قديمة جديدة للمراجعة.'); } catch { setError('تعذر قراءة رسائل التحويل القديمة'); } }
  async function recordExpense(review: WalletTransferReview) { if (!categoryId || !beneficiary.trim() || !reason.trim()) { setError('اختر التصنيف واكتب المستفيد والسبب أولاً'); return; } try { await platformFinanceService.recordWalletTransferExpense(review.id, { categoryId, beneficiaryName: beneficiary, reason }); setEditing(null); setBeneficiary(''); setReason(''); setCategoryId(''); await load(); } catch { setError('تعذر تسجيل التحويل كمصروف'); } }
  async function recordInternal(review: WalletTransferReview) { if (!destinationTreasuryId) { setError('اختر محفظة المنصة المستلمة أولاً'); return; } if (review.serviceFee > 0) { setError('هذا التحويل به رسوم؛ سجّله كمصروف حتى تُحتسب الرسوم بدقة.'); return; } try { await platformFinanceService.recordWalletInternalTransfer(review.id, destinationTreasuryId); setEditing(null); setDestinationTreasuryId(''); await load(); } catch { setError('تعذر تسجيل التحويل الداخلي'); } }
  return <section className="admin-panel rounded-2xl p-6" dir="rtl"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black">مصروفات المنصة</h2><button className="admin-btn-ghost" type="button" onClick={() => void load()}>تحديث</button></div>{error ? <p role="alert" className="mb-3 text-rose-600">{error}</p> : null}
    <div className="mb-6 rounded-2xl border border-amber-300/70 bg-amber-50/60 p-4 dark:bg-amber-950/20"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black">تحويلات المحافظ بانتظار التصنيف ({reviews.length})</h3><p className="mt-1 text-sm text-[var(--admin-muted)]">لا تظهر كمصروف في المركز المالي قبل اختيار المعالجة المناسبة.</p></div><button type="button" className="admin-btn-ghost" onClick={() => void backfill()}>قراءة رسائل التحويل القديمة</button></div>{reviews.length === 0 ? <p className="py-3 text-sm text-[var(--admin-muted)]">لا توجد تحويلات معلّقة.</p> : <div className="mt-3 space-y-3">{reviews.map(review => <div key={review.id} className="rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface)] p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><b>{money(review.amount + review.serviceFee)}</b> <span className="text-sm">من {review.sourceWallet} إلى {review.destinationPhoneNumber}</span>{review.serviceFee > 0 ? <span className="mr-2 text-xs text-amber-700">يشمل رسوم {money(review.serviceFee)}</span> : null}</div><button type="button" className="admin-btn-ghost text-sm" onClick={() => setEditing(editing === review.id ? null : review.id)}>تصنيف الحركة</button></div>{editing === review.id ? <div className="mt-3 grid gap-2 md:grid-cols-2"><select value={categoryId} onChange={e => setCategoryId(e.target.value)} className="admin-input"><option value="">تصنيف المصروف</option>{bootstrap?.categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select><input className="admin-input" value={beneficiary} onChange={e => setBeneficiary(e.target.value)} placeholder="المستفيد / الجهة" /><input className="admin-input" value={reason} onChange={e => setReason(e.target.value)} placeholder="سبب التحويل" /><button type="button" className="admin-btn-primary" onClick={() => void recordExpense(review)}>تسجيل كمصروف</button><select value={destinationTreasuryId} onChange={e => setDestinationTreasuryId(e.target.value)} className="admin-input"><option value="">محفظة منصة مستلمة (تحويل داخلي)</option>{bootstrap?.treasuryAccounts.filter(account => account.id !== review.sourceTreasuryAccountId).map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select><button type="button" className="admin-btn-ghost" onClick={() => void recordInternal(review)}>تسجيل تحويل داخلي</button></div> : null}</div>)}</div>}</div>
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-right"><th>المستند</th><th>الوصف</th><th>التاريخ</th><th>المبلغ</th><th>المدفوع</th><th>الحالة</th><th /></tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-t border-[var(--admin-border)]"><td>{row.documentNumber}</td><td>{row.description}</td><td>{new Date(row.occurredAt).toLocaleDateString('ar-EG')}</td><td>{money(row.amount)}</td><td>{money(row.paid)}</td><td>{row.status === 5 ? 'معكوس' : row.status === 4 ? 'مدفوع' : row.status === 3 ? 'مدفوع جزئيًا' : row.status === 2 ? 'آجل' : 'مسودة'}</td><td>{row.status !== 5 && row.status !== 1 ? <button className="text-rose-600" type="button" onClick={() => void reverse(row.id)}>عكس</button> : null}</td></tr>)}</tbody></table>{rows.length === 0 ? <p className="py-8 text-center text-[var(--admin-muted)]">لا توجد مصروفات.</p> : null}</div></section>;
}
