import React, {useEffect,useState} from 'react';
import {api,copyText,number,toast} from '../../web/assets/common.js';
export const sendStates={accepted:'قبل واتساب الرسالة',failed:'لم تُرسل',rejected:'رفض واتساب الطلب',unknown:'غير مؤكدة — راجع واتساب',preparing:'تجهيز التقرير',sending:'جارٍ الإرسال'};
export const templateText=t=>(t?.components||[]).find(c=>c.type==='BODY')?.text||'';
export function TemplateFields({templates,templateId,setTemplateId,mappings,setMappings,disabled=false}) {
  const selected=templates.find(t=>t.id===templateId);
  const positions=[...new Set([...templateText(selected).matchAll(/\{\{\s*(\d+)\s*\}\}/g)].map(m=>Number(m[1])))].sort((a,b)=>a-b);
  const choose=id=>{setTemplateId(id);setMappings([]);};
  const change=(index,values)=>setMappings(positions.map((_,i)=>i===index?{...mappings[i],...values}:mappings[i]||{source:''}));
  return <><label>قالب إرفاق التقرير<select disabled={disabled} value={templateId} onChange={e=>choose(e.target.value)}><option value="">اختر قالبًا معتمدًا فيه مستند PDF</option>{templates.filter(t=>t.reportSupported).map(t=><option key={t.id} value={t.id}>{t.name} · {t.language}</option>)}</select></label>
    {selected&&<><div className="whatsapp-message" dir="auto">{templateText(selected)}</div><div className="whatsapp-fields">{positions.map((position,index)=><div key={position}><label>بيانات المتغير {number(position)}<select disabled={disabled} value={mappings[index]?.source||''} onChange={e=>change(index,{source:e.target.value})}><option value="">اختر بيانات الطالب</option>{Object.entries({name:'اسم الطالب',code:'كود الطالب',result:'جاب كام من كام',score:'الدرجة',maximum:'الدرجة النهائية',exam:'اسم الامتحان',literal:'نص ثابت'}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{mappings[index]?.source==='literal'&&<label>النص الثابت<input disabled={disabled} maxLength={1000} value={mappings[index]?.text||''} onChange={e=>change(index,{text:e.target.value})}/></label>}</div>)}</div></>}
  </>;
}
export default function WhatsApp({token}) {
  const [settings,setSettings]=useState(null),[templates,setTemplates]=useState([]),[history,setHistory]=useState([]);
  const [form,setForm]=useState({phoneNumberId:'',businessAccountId:'',apiVersion:'v23.0',accessToken:'',appSecret:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async()=>{const [config,cache,sends]=await Promise.all([api('/api/whatsapp/configuration'),api('/api/whatsapp/templates'),api('/api/whatsapp/history')]);setSettings(config);setTemplates(cache.templates);setHistory(sends.items);setForm(f=>({...f,phoneNumberId:config.phoneNumberId||'',businessAccountId:config.businessAccountId||'',apiVersion:config.apiVersion||'v23.0',accessToken:'',appSecret:''}));setError('');};
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  const perform=async action=>{setBusy(true);try{await action();}catch(e){toast(e.message,true);}finally{setBusy(false);}};
  if(error)return <section className="panel"><h1>تعذر قراءة إعدادات واتساب</h1><p>{error}</p><button className="button" onClick={()=>load().catch(e=>setError(e.message))}>إعادة المحاولة</button></section>;
  if(!settings)return <div className="loading">جارٍ قراءة إعدادات واتساب…</div>;
  return <><div className="page-heading"><div><span className="context-label">تقارير الطلاب</span><h1>واتساب السنتر</h1><p>اربط الحساب، واختر القالب المعتمد. إرسال التقارير متاح من نتائج القاعة أو الشيتات.</p></div><span className={`badge ${settings.configured?'complete':'quiet'}`}>{settings.configured?'بيانات الحساب محفوظة':'أكمل ربط الحساب'}</span></div>
    <section className="panel"><h2>الحساب الرسمي</h2><p className="help">انسخ الرقمين المختلفين من WhatsApp ← API Setup. يلزم إنترنت على جهاز الإدارة للمزامنة والإرسال.</p><form onSubmit={e=>{e.preventDefault();perform(async()=>{await api('/api/whatsapp/configuration',form,token);await load();toast('تم حفظ إعدادات واتساب');});}}><div className="whatsapp-fields">{[['phoneNumberId','Phone Number ID'],['businessAccountId','WhatsApp Business Account ID'],['apiVersion','نسخة Meta API']].map(([key,label])=><label key={key}>{label}<input required dir="ltr" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value.trim()})}/></label>)}</div><label>توكن واتساب{settings.tokenConfigured?' · محفوظ':''}<input type="password" autoComplete="off" required={!settings.tokenConfigured} value={form.accessToken} onChange={e=>setForm({...form,accessToken:e.target.value.trim()})} placeholder={settings.tokenConfigured?'اتركه فارغًا لاستخدام المحفوظ':'الصق التوكن هنا'}/></label><label>App Secret{settings.appSecretConfigured?' · محفوظ':''}<input type="password" autoComplete="off" value={form.appSecret} onChange={e=>setForm({...form,appSecret:e.target.value.trim()})} placeholder="سر تطبيق Meta الخاص بالويب هوك"/></label><p className="help">المفاتيح محفوظة في ملف خاص على الجهاز خارج قاعدة البيانات والنسخ الاحتياطية. عند نقل البرنامج إلى جهاز آخر، اربط الحساب عليه مرة أخرى.</p><button className="button" disabled={busy}>حفظ الحساب</button></form></section>
    <section className="panel"><div className="section-top"><div><h2>القوالب الرسمية</h2><p className="help">{number(templates.length)} قالب · {number(templates.filter(t=>t.reportSupported).length)} يصلح لإرفاق PDF. القالب يحتاج رأسًا من نوع Document / مستند.</p></div><button className="button secondary" disabled={busy||!settings.configured} onClick={()=>perform(async()=>{await api('/api/whatsapp/templates/sync',{},token,{timeoutMs:120000});await load();toast('تم تحديث القوالب والتحقق من رقم الإرسال');})}>مزامنة القوالب من Meta</button></div><div className="whatsapp-templates">{templates.length?templates.map(t=><article className="whatsapp-template" key={t.id}><div className="section-top"><strong dir="ltr">{t.name}</strong><span className={`badge ${t.reportSupported?'complete':'quiet'}`}>{t.status==='APPROVED'?'معتمد':t.status}</span></div><p className="help">{t.language} · {t.category}</p><p className="whatsapp-message" dir="auto">{templateText(t)}</p><p className="help">{t.reportSupported?'جاهز لإرفاق تقرير الطالب':t.reportReason}</p></article>):<p className="empty">احفظ الحساب ثم زامن القوالب لتظهر هنا.</p>}</div></section>
    {settings.verifyToken&&<section className="panel"><h2>ربط الويب هوك</h2><p className="help">الويب هوك يحتاج رابط HTTPS عامًا على المنصة. هذا الرمز لتأكيد الرابط في Meta؛ إعدادات الإرسال تعمل من البرنامج.</p><label>Verify Token<input readOnly dir="ltr" value={settings.verifyToken}/></label><button className="button secondary" onClick={()=>copyText(settings.verifyToken)}>نسخ رمز التحقق</button></section>}
    <section className="panel"><div className="section-top"><div><h2>سجل إرسال التقارير</h2><p className="help">«قبل واتساب الرسالة» تأكيد قبول الطلب، ويختلف عن وصولها أو قراءتها. الحالة غير المؤكدة لا يعاد إرسالها تلقائيًا.</p></div><button className="text-button" disabled={busy} onClick={()=>perform(load)}>تحديث السجل</button></div><div className="table-scroll"><table><thead><tr><th>الطالب</th><th>التقرير</th><th>الحالة</th></tr></thead><tbody>{history.length?history.map((row,i)=><tr key={i}><td><strong>{row.name}</strong><small dir="ltr">{row.code} · {row.phone}</small></td><td>{row.filename}<small dir="ltr">{row.template}</small></td><td>{sendStates[row.state]||row.state}<small>{row.error}</small></td></tr>):<tr><td colSpan={3} className="empty">لم تُرسل تقارير بعد.</td></tr>}</tbody></table></div></section></>;
}
