'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { ChevronDown, ChevronUp, Loader2, Play } from 'lucide-react';
import toast from 'react-hot-toast';
import { EmployeePayrollDto, hrPayrollService, PayrollRunDto } from '@/services/hr-payroll-service';
import { cairoCurrentMonthPeriod } from '@/lib/cairo-time';

const actions: Record<string, { action: 'finance-review' | 'finance-approve' | 'gm-approve' | 'pay' | 'close'; label: string }> = { Prepared: { action: 'finance-review', label: 'بدء مراجعة المالية' }, FinanceReview: { action: 'finance-approve', label: 'اعتماد المالية' }, FinanceApproved: { action: 'gm-approve', label: 'اعتماد المدير العام' }, GMApproved: { action: 'pay', label: 'تأكيد الصرف' }, Paid: { action: 'close', label: 'إغلاق الدورة' } };
export function PayrollRunWorkspace() {
  const { first, last } = cairoCurrentMonthPeriod();
  const [runs, setRuns] = useState<PayrollRunDto[]>([]); const [details, setDetails] = useState<Record<string, EmployeePayrollDto[]>>({}); const [expanded, setExpanded] = useState<string>(); const [loading, setLoading] = useState(true); const [period, setPeriod] = useState({ periodStart: first, periodEnd: last });
  const load = useCallback(async () => { setLoading(true); try { setRuns(await hrPayrollService.runs()); } catch { toast.error('تعذر تحميل دورات الرواتب'); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  async function prepare(event: FormEvent) { event.preventDefault(); try { await hrPayrollService.prepare({ ...period, cutoffAt: new Date().toISOString() }); toast.success('تم إعداد الدورة ولقطة بياناتها'); await load(); } catch { toast.error('تعذر إعداد الدورة'); } }
  async function toggle(run: PayrollRunDto) { if (expanded === run.id) return setExpanded(undefined); if (!details[run.id]) setDetails((old) => ({ ...old, [run.id]: [] })); const rows = await hrPayrollService.run(run.id); setDetails((old) => ({ ...old, [run.id]: rows })); setExpanded(run.id); }
  async function move(run: PayrollRunDto) { const next = actions[run.status]; if (!next) return; try { await hrPayrollService.transition(run.id, next.action, run.version); toast.success('تم نقل الدورة للمرحلة التالية'); await load(); } catch { toast.error('الانتقال غير مسموح أو النسخة تغيرت'); } }
  if (loading) return <div className="admin-panel py-16 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin" /></div>;
  return <div className="space-y-5"><form onSubmit={prepare} className="admin-panel"><div className="flex flex-wrap items-end gap-3"><label className="text-sm font-bold">بداية الفترة<input type="date" value={period.periodStart} onChange={(e) => setPeriod({ ...period, periodStart: e.target.value })} className="admin-input mt-2" /></label><label className="text-sm font-bold">نهاية الفترة<input type="date" value={period.periodEnd} onChange={(e) => setPeriod({ ...period, periodEnd: e.target.value })} className="admin-input mt-2" /></label><button className="admin-btn-primary inline-flex min-h-11 items-center gap-2"><Play className="h-4 w-4" />إعداد الدورة</button></div></form>{runs.map((run) => <article key={run.id} className="admin-panel"><div className="flex flex-wrap items-center justify-between gap-3"><button onClick={() => void toggle(run)} className="flex min-h-11 items-center gap-3 text-right"><span>{expanded === run.id ? <ChevronUp /> : <ChevronDown />}</span><span><b className="block">{run.runNumber}</b><small className="text-[var(--admin-muted)]">{run.periodStart} — {run.periodEnd} · {run.employees} موظف</small></span></button><div className="text-left"><span className="admin-badge">{run.status}</span><p className="mt-2 text-xl font-black">{run.totalNet.toLocaleString('ar-EG')} ج.م</p></div></div>{actions[run.status] && <button onClick={() => void move(run)} className="admin-btn-primary mt-4 min-h-11">{actions[run.status].label}</button>}{expanded === run.id && <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="text-right text-[var(--admin-muted)]"><th className="p-3">الموظف</th><th className="p-3">الإجمالي</th><th className="p-3">الخصومات</th><th className="p-3">الصافي</th><th className="p-3">الشرح</th></tr></thead><tbody>{(details[run.id] ?? []).map((row) => <tr key={row.id} className="border-t border-[var(--admin-border)]"><td className="p-3 font-black">{row.employeeNameSnapshot}<small className="block text-[var(--admin-muted)]">{row.employeeNumberSnapshot}</small></td><td className="p-3">{row.gross}</td><td className="p-3">{row.deductions}</td><td className="p-3 font-black">{row.net}</td><td className="p-3 text-xs">{row.lines.map((line) => line.explanation).join(' · ')}</td></tr>)}</tbody></table></div>}</article>)}</div>;
}
