'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Loader2, Plus } from 'lucide-react';
import toast from 'react-hot-toast';
import { hrPayrollService, PayComponentClass, PayComponentDto, PayrollRuleDto } from '@/services/hr-payroll-service';

export function PayrollRuleEditor() {
  const [components, setComponents] = useState<PayComponentDto[]>([]); const [rules, setRules] = useState<PayrollRuleDto[]>([]); const [loading, setLoading] = useState(true);
  const [component, setComponent] = useState({ code: '', name: '', classification: 'Earning' as PayComponentClass, isTaxable: false, isInsurable: false });
  const [rule, setRule] = useState({ payComponentId: '', name: '', expression: 'fixed:0', rate: 0, effectiveFrom: new Date().getFullYear() + '-01-01', priority: 10 });
  const load = useCallback(async () => { setLoading(true); try { const data = await hrPayrollService.config(); setComponents(data.components); setRules(data.rules); setRule((old) => ({ ...old, payComponentId: old.payComponentId || data.components[0]?.id || '' })); } catch { toast.error('تعذر تحميل قواعد الرواتب'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function addComponent(event: FormEvent) { event.preventDefault(); try { await hrPayrollService.createComponent(component); toast.success('تم إنشاء المكوّن'); setComponent({ ...component, code: '', name: '' }); await load(); } catch { toast.error('تعذر إنشاء المكوّن'); } }
  async function addRule(event: FormEvent) { event.preventDefault(); try { await hrPayrollService.createRule({ ...rule, effectiveTo: null }); toast.success('تم نشر نسخة القاعدة'); setRule({ ...rule, name: '' }); await load(); } catch { toast.error('المعادلة غير مسموحة أو البيانات متعارضة'); } }
  if (loading) return <div className="admin-panel py-16 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin" /></div>;
  return <div className="grid gap-5 xl:grid-cols-2"><form onSubmit={addComponent} className="admin-panel"><h2 className="text-lg font-black">مكوّن راتب</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">الكود<input required value={component.code} onChange={(e) => setComponent({ ...component, code: e.target.value })} className="admin-input mt-2" /></label><label className="text-sm font-bold">الاسم<input required value={component.name} onChange={(e) => setComponent({ ...component, name: e.target.value })} className="admin-input mt-2" /></label><label className="text-sm font-bold">التصنيف<select value={component.classification} onChange={(e) => setComponent({ ...component, classification: e.target.value as PayComponentClass })} className="admin-input mt-2"><option value="Earning">استحقاق</option><option value="Deduction">استقطاع</option><option value="EmployerContribution">مساهمة جهة العمل</option><option value="Informational">معلومة</option></select></label></div><div className="mt-4 flex gap-4 text-sm font-bold"><label><input type="checkbox" checked={component.isTaxable} onChange={(e) => setComponent({ ...component, isTaxable: e.target.checked })} /> خاضع للضريبة</label><label><input type="checkbox" checked={component.isInsurable} onChange={(e) => setComponent({ ...component, isInsurable: e.target.checked })} /> خاضع للتأمين</label></div><button className="admin-btn-primary mt-5 inline-flex min-h-11 items-center gap-2"><Plus className="h-4 w-4" />إضافة</button></form>
  <form onSubmit={addRule} className="admin-panel"><h2 className="text-lg font-black">قاعدة حساب مؤرخة</h2><p className="mt-1 text-xs text-[var(--admin-muted)]">المتاح: base، fixed:500، percentage:10، أو attendance.late_minutes * rate ونظائر الغياب والإضافي.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">المكوّن<select value={rule.payComponentId} onChange={(e) => setRule({ ...rule, payComponentId: e.target.value })} className="admin-input mt-2">{components.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-bold">اسم القاعدة<input required value={rule.name} onChange={(e) => setRule({ ...rule, name: e.target.value })} className="admin-input mt-2" /></label><label className="text-sm font-bold sm:col-span-2">المعادلة<input dir="ltr" required value={rule.expression} onChange={(e) => setRule({ ...rule, expression: e.target.value })} className="admin-input mt-2 font-mono" /></label><label className="text-sm font-bold">المعدل<input type="number" step="0.0001" value={rule.rate} onChange={(e) => setRule({ ...rule, rate: Number(e.target.value) })} className="admin-input mt-2" /></label><label className="text-sm font-bold">السريان<input type="date" value={rule.effectiveFrom} onChange={(e) => setRule({ ...rule, effectiveFrom: e.target.value })} className="admin-input mt-2" /></label></div><button className="admin-btn-primary mt-5 inline-flex min-h-11 items-center gap-2"><Plus className="h-4 w-4" />نشر نسخة</button></form>
  <section className="admin-panel xl:col-span-2"><h2 className="text-lg font-black">القواعد المنشورة</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="text-right text-[var(--admin-muted)]"><th className="p-3">المكوّن</th><th className="p-3">القاعدة</th><th className="p-3">المعادلة</th><th className="p-3">الإصدار</th><th className="p-3">السريان</th></tr></thead><tbody>{rules.map((item) => <tr key={item.id} className="border-t border-[var(--admin-border)]"><td className="p-3 font-black">{item.component}</td><td className="p-3">{item.name}</td><td className="p-3 font-mono" dir="ltr">{item.expression}</td><td className="p-3">v{item.version}</td><td className="p-3">{item.effectiveFrom}</td></tr>)}</tbody></table></div></section></div>;
}
