// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NaderGorge.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NaderGorge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408164959_AddLessonCommentsModeration")]
    partial class AddLessonCommentsModeration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NaderGorge.Domain.Entities.AccessCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodePlaintext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ConsumedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeGroupId");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("ConsumedByUserId");

                    b.ToTable("access_codes", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Assistant.AssistantTaskQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAssistantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ReferenceEntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAssistantId");

                    b.HasIndex("StudentId");

                    b.ToTable("assistant_tasks", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.BalanceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentBalanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentBalanceId");

                    b.ToTable("balance_transactions", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.CodeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BalanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CodeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ContentSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("QrDataGenerated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalCodes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("code_groups", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.CodeVideoTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LessonVideoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LessonVideoId");

                    b.HasIndex("CodeGroupId", "LessonVideoId")
                        .IsUnique();

                    b.ToTable("code_video_targets", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.ContentSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TermId");

                    b.ToTable("content_sections", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceFingerprint")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.EssaySubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text");

                    b.Property<decimal?>("AiInitialScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentExamAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeacherFeedback")
                        .HasColumnType("text");

                    b.Property<decimal?>("TeacherFinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentExamAttemptId");

                    b.HasIndex("StudentId");

                    b.ToTable("essay_submissions", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRandomized")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PassingScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TimePerQuestionSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal>("Points")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("QuestionBankItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankItemId");

                    b.HasIndex("ExamId", "QuestionBankItemId")
                        .IsUnique();

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.ExtraWatchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LessonVideoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonVideoId");

                    b.HasIndex("UserId");

                    b.ToTable("ExtraWatchRequests");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Gamification.GamificationActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("gamification_action_logs", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Gamification.StudentBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("student_badges", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Gamification.StudentGamification", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStreakCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastTaskCompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LongestStreakCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.HasKey("StudentId");

                    b.ToTable("student_gamifications", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Homework.Homework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRandomized")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PassingScoreThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("homeworks", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Homework.HomeworkAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeworkSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProvidedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ScoreReceived")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HomeworkSubmissionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("homework_answers", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Homework.HomeworkQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswerKey")
                        .HasColumnType("text");

                    b.Property<Guid>("HomeworkId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PointsActive")
                        .HasColumnType("integer");

                    b.Property<string[]>("PossibleAnswers")
                        .HasColumnType("text[]");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HomeworkId");

                    b.ToTable("homework_questions", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Homework.HomeworkSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssistantNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("AssistantReviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Evaluation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("HomeworkId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssistantReviewerId");

                    b.HasIndex("HomeworkId");

                    b.HasIndex("StudentId");

                    b.ToTable("homework_submissions", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentSectionId");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.LessonComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LessonId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("lesson_comments", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.LessonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManuallyUnlocked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("lesson_progress", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.LessonResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("lesson_resources", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.LessonVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProcessingAI")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessingMindmaps")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxWatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderVideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubtitleUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VideoTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("LessonId");

                    b.ToTable("lesson_videos", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Notifications.NotificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChannelType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notification_events", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.PlatformSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlatformSettings");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.QuestionBankItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("DefaultPoints")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HintText")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WrittenCorrection")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("question_bank_items", (string)null);

                    b.HasDiscriminator<int>("Type").HasValue(1);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionBankItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankItemId");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceFingerprint")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Student.StudentStatusTracker", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailedExams")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveMissedHomeworks")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastEvaluatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("StudentId");

                    b.ToTable("student_status_trackers", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Student.WarningEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ResolvedByAssistantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedByAssistantId");

                    b.HasIndex("StudentId");

                    b.ToTable("warning_events", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessCodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContentSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GrantType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LessonVideoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccessCodeId");

                    b.HasIndex("UserId", "PackageId");

                    b.ToTable("student_access_grants", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PointsAwarded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentExamAttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamQuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("StudentExamAttemptId", "ExamQuestionId")
                        .IsUnique();

                    b.ToTable("student_answers", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("student_balances", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Evaluation")
                        .HasColumnType("text");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTimeExpired")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ScoreAchieved")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("student_exam_attempts", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("District")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EducationStage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FatherDateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFatherAlive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMotherAlive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MotherDateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MotherPhone")
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("ParentPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SchoolName")
                        .HasColumnType("text");

                    b.Property<int?>("SchoolType")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryParentPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("StudyTrack")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.TeacherPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("teacher_photos", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("terms", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.VideoChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EndTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("LessonVideoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MindmapImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("StartTime")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LessonVideoId");

                    b.ToTable("video_chapters", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.VideoPlaybackSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonVideoId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonVideoId");

                    b.HasIndex("UserId");

                    b.ToTable("VideoPlaybackSessions");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.VideoWatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonVideoId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeWatchedInSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WatchCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonVideoId");

                    b.HasIndex("UserId", "LessonVideoId")
                        .IsUnique();

                    b.ToTable("video_watch_events", (string)null);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.FindTheMistakeQuestion", b =>
                {
                    b.HasBaseType("NaderGorge.Domain.Entities.QuestionBankItem");

                    b.Property<string>("BaseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MistakeEndIndex")
                        .HasColumnType("integer");

                    b.Property<int>("MistakeStartIndex")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.AccessCode", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.CodeGroup", "CodeGroup")
                        .WithMany("AccessCodes")
                        .HasForeignKey("CodeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "ConsumedByUser")
                        .WithMany()
                        .HasForeignKey("ConsumedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CodeGroup");

                    b.Navigation("ConsumedByUser");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Assistant.AssistantTaskQueue", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "AssignedAssistant")
                        .WithMany()
                        .HasForeignKey("AssignedAssistantId");

                    b.HasOne("NaderGorge.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedAssistant");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.BalanceTransaction", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.StudentBalance", "StudentBalance")
                        .WithMany("Transactions")
                        .HasForeignKey("StudentBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentBalance");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.CodeGroup", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.CodeVideoTarget", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.CodeGroup", "CodeGroup")
                        .WithMany("CodeVideoTargets")
                        .HasForeignKey("CodeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.LessonVideo", "LessonVideo")
                        .WithMany()
                        .HasForeignKey("LessonVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeGroup");

                    b.Navigation("LessonVideo");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.ContentSection", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Term", "Term")
                        .WithMany("Sections")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Term");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Device", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.EssaySubmission", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.QuestionBankItem", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.StudentExamAttempt", "Attempt")
                        .WithMany()
                        .HasForeignKey("StudentExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.QuestionBankItem", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionBankItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.ExtraWatchRequest", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.LessonVideo", "LessonVideo")
                        .WithMany()
                        .HasForeignKey("LessonVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonVideo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Gamification.GamificationActionLog", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Gamification.StudentBadge", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Gamification.StudentGamification", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "Student")
                        .WithOne()
                        .HasForeignKey("NaderGorge.Domain.Entities.Gamification.StudentGamification", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Homework.HomeworkAnswer", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Homework.HomeworkSubmission", "Submission")
                        .WithMany("Answers")
                        .HasForeignKey("HomeworkSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.Homework.HomeworkQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Homework.HomeworkQuestion", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Homework.Homework", "Homework")
                        .WithMany("Questions")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Homework");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Homework.HomeworkSubmission", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "AssistantReviewer")
                        .WithMany()
                        .HasForeignKey("AssistantReviewerId");

                    b.HasOne("NaderGorge.Domain.Entities.Homework.Homework", "Homework")
                        .WithMany("Submissions")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssistantReviewer");

                    b.Navigation("Homework");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.ContentSection", "ContentSection")
                        .WithMany("Lessons")
                        .HasForeignKey("ContentSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentSection");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.LessonComment", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Comments")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AuthorUser");

                    b.Navigation("Lesson");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.LessonProgress", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.LessonResource", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Resources")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.LessonVideo", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId");

                    b.HasOne("NaderGorge.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Videos")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Notifications.NotificationEvent", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Package", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Program", "Program")
                        .WithMany("Packages")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.QuestionBankItem", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionBankItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Student.StudentStatusTracker", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "Student")
                        .WithOne()
                        .HasForeignKey("NaderGorge.Domain.Entities.Student.StudentStatusTracker", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Student.WarningEvent", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "ResolvedByAssistant")
                        .WithMany()
                        .HasForeignKey("ResolvedByAssistantId");

                    b.HasOne("NaderGorge.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolvedByAssistant");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentAccessGrant", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.AccessCode", "AccessCode")
                        .WithMany()
                        .HasForeignKey("AccessCodeId");

                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentAnswer", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.StudentExamAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("StudentExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("ExamQuestion");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentBalance", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithOne("StudentBalance")
                        .HasForeignKey("NaderGorge.Domain.Entities.StudentBalance", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentExamAttempt", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("NaderGorge.Domain.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.TeacherPhoto", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Term", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Package", "Package")
                        .WithMany("Terms")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.VideoChapter", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.LessonVideo", "LessonVideo")
                        .WithMany("VideoChapters")
                        .HasForeignKey("LessonVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonVideo");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.VideoPlaybackSession", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.LessonVideo", "LessonVideo")
                        .WithMany()
                        .HasForeignKey("LessonVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonVideo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.VideoWatchEvent", b =>
                {
                    b.HasOne("NaderGorge.Domain.Entities.LessonVideo", "LessonVideo")
                        .WithMany()
                        .HasForeignKey("LessonVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NaderGorge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonVideo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.CodeGroup", b =>
                {
                    b.Navigation("AccessCodes");

                    b.Navigation("CodeVideoTargets");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.ContentSection", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Exam", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Homework.Homework", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Homework.HomeworkSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Resources");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.LessonVideo", b =>
                {
                    b.Navigation("VideoChapters");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Package", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Program", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.QuestionBankItem", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentBalance", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.StudentExamAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.Term", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("NaderGorge.Domain.Entities.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StudentBalance");

                    b.Navigation("StudentProfile");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
