'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Loader2, Plus } from 'lucide-react';
import toast from 'react-hot-toast';
import { hrService, LeavePolicyDto, LeaveTypeDto, WorkCalendarDto } from '@/services/hr-service';

export function LeaveAdministration() {
  const [types, setTypes] = useState<LeaveTypeDto[]>([]); const [policies, setPolicies] = useState<LeavePolicyDto[]>([]); const [calendars, setCalendars] = useState<WorkCalendarDto[]>([]); const [loading, setLoading] = useState(true);
  const [typeForm, setTypeForm] = useState({ code: '', name: '', isPaid: true, requiresAttachment: false, allowsHalfDay: true });
  const [policy, setPolicy] = useState({ name: '', leaveTypeId: '', annualEntitlement: 21, maximumCarryover: 0, allowNegativeBalance: false, effectiveFrom: new Date().getFullYear() + '-01-01', workCalendarId: '' });
  const load = useCallback(async () => { setLoading(true); try { const [config, calendarRows] = await Promise.all([hrService.getLeaveConfiguration(), hrService.listWorkCalendars()]); setTypes(config.types); setPolicies(config.policies); setCalendars(calendarRows); setPolicy((old) => ({ ...old, leaveTypeId: old.leaveTypeId || config.types[0]?.id || '', workCalendarId: old.workCalendarId || calendarRows[0]?.id || '' })); } catch { toast.error('تعذر تحميل إعدادات الإجازات'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function addType(event: FormEvent) { event.preventDefault(); try { await hrService.createLeaveType(typeForm); toast.success('تم إنشاء نوع الإجازة'); setTypeForm({ ...typeForm, code: '', name: '' }); await load(); } catch { toast.error('تعذر إنشاء النوع'); } }
  async function addPolicy(event: FormEvent) { event.preventDefault(); try { await hrService.createLeavePolicy({ ...policy, effectiveTo: null }); toast.success('تم تفعيل السياسة'); setPolicy({ ...policy, name: '' }); await load(); } catch { toast.error('تعذر إنشاء السياسة'); } }
  if (loading) return <div className="admin-panel py-16 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin" /></div>;
  return <div className="grid gap-5 xl:grid-cols-2"><form onSubmit={addType} className="admin-panel"><h2 className="text-lg font-black">نوع إجازة</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">الكود<input required value={typeForm.code} onChange={(e) => setTypeForm({ ...typeForm, code: e.target.value })} className="admin-input mt-2" /></label><label className="text-sm font-bold">الاسم<input required value={typeForm.name} onChange={(e) => setTypeForm({ ...typeForm, name: e.target.value })} className="admin-input mt-2" /></label></div><div className="mt-4 flex flex-wrap gap-4 text-sm font-bold"><label><input type="checkbox" checked={typeForm.isPaid} onChange={(e) => setTypeForm({ ...typeForm, isPaid: e.target.checked })} /> مدفوعة</label><label><input type="checkbox" checked={typeForm.requiresAttachment} onChange={(e) => setTypeForm({ ...typeForm, requiresAttachment: e.target.checked })} /> تتطلب مرفقًا</label><label><input type="checkbox" checked={typeForm.allowsHalfDay} onChange={(e) => setTypeForm({ ...typeForm, allowsHalfDay: e.target.checked })} /> تسمح بنصف يوم</label></div><button className="admin-btn-primary mt-5 inline-flex min-h-11 items-center gap-2"><Plus className="h-4 w-4" />إضافة النوع</button></form>
  <form onSubmit={addPolicy} className="admin-panel"><h2 className="text-lg font-black">سياسة استحقاق</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">اسم السياسة<input required value={policy.name} onChange={(e) => setPolicy({ ...policy, name: e.target.value })} className="admin-input mt-2" /></label><label className="text-sm font-bold">نوع الإجازة<select value={policy.leaveTypeId} onChange={(e) => setPolicy({ ...policy, leaveTypeId: e.target.value })} className="admin-input mt-2">{types.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-bold">الاستحقاق السنوي<input type="number" min="0" value={policy.annualEntitlement} onChange={(e) => setPolicy({ ...policy, annualEntitlement: Number(e.target.value) })} className="admin-input mt-2" /></label><label className="text-sm font-bold">حد الترحيل<input type="number" min="0" value={policy.maximumCarryover} onChange={(e) => setPolicy({ ...policy, maximumCarryover: Number(e.target.value) })} className="admin-input mt-2" /></label><label className="text-sm font-bold">تاريخ السريان<input type="date" value={policy.effectiveFrom} onChange={(e) => setPolicy({ ...policy, effectiveFrom: e.target.value })} className="admin-input mt-2" /></label><label className="text-sm font-bold">تقويم العمل<select value={policy.workCalendarId} onChange={(e) => setPolicy({ ...policy, workCalendarId: e.target.value })} className="admin-input mt-2">{calendars.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div><label className="mt-4 block text-sm font-bold"><input type="checkbox" checked={policy.allowNegativeBalance} onChange={(e) => setPolicy({ ...policy, allowNegativeBalance: e.target.checked })} /> السماح برصيد سالب</label><button className="admin-btn-primary mt-5 inline-flex min-h-11 items-center gap-2"><Plus className="h-4 w-4" />تفعيل السياسة</button></form>
  <section className="admin-panel xl:col-span-2"><h2 className="text-lg font-black">السياسات الفعالة</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{policies.map((item) => <article key={item.id} className="rounded-2xl bg-[var(--admin-card-soft)] p-4"><p className="font-black">{item.name}</p><p className="mt-1 text-sm text-[var(--admin-muted)]">{item.leaveType} · {item.annualEntitlement} يوم سنويًا · ترحيل {item.maximumCarryover}</p></article>)}</div></section></div>;
}
