'use client';
import { useCallback, useEffect, useState } from 'react';
import { Check, MessageSquareText, X } from 'lucide-react';
import toast from 'react-hot-toast';
import { AdminPage, AdminPageSkeleton } from '@/components/admin';
import { adminService, type ModerationLessonCommentDto } from '@/services/admin-service';
import { teacherService, type TeacherDto } from '@/services/teacher-service';

export default function AdminCommentsPageClient() {
  const [comments, setComments] = useState<ModerationLessonCommentDto[]>([]); const [teachers, setTeachers] = useState<TeacherDto[]>([]); const [teacherId, setTeacherId] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async (selected = '') => { try { setLoading(true); setComments(await adminService.getAllLessonComments(selected)); } catch { toast.error('تعذر تحميل التعليقات'); } finally { setLoading(false); } }, []);
  useEffect(() => { void teacherService.getTeachers().then(res => setTeachers(res.data ?? [])); void load(''); }, [load]);
  const moderate = async (id: string, approved: boolean) => { try { await (approved ? adminService.approveLessonComment(id) : adminService.rejectLessonComment(id)); await load(teacherId); } catch { toast.error('تعذر تحديث التعليق'); } };
  return <AdminPage activePath="/admin/comments" sectionLabel="المتابعة والتفاعل" pageTitle="تعليقات الطلاب" subtitle="اختر المدرس لمراجعة كل تعليقات حصصه من مكان واحد."><div className="mb-6 max-w-md"><label className="mb-2 block text-sm font-black text-[var(--admin-text)]">المدرس</label><select value={teacherId} onChange={event => { setTeacherId(event.target.value); void load(event.target.value); }} className="admin-input w-full"><option value="">كل المدرسين</option>{teachers.map(teacher => <option key={teacher.id} value={teacher.id}>{teacher.fullName}</option>)}</select></div>{loading ? <AdminPageSkeleton /> : <div className="space-y-4">{comments.length === 0 ? <div className="admin-panel py-16 text-center"><MessageSquareText className="mx-auto h-10 w-10 text-[var(--admin-muted)]" /><p className="mt-3 font-black">لا توجد تعليقات</p></div> : comments.map(comment => <article key={comment.id} className="admin-panel"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-black">{comment.studentName}</p><p className="mt-1 text-xs font-bold text-[var(--admin-muted)]">{new Date(comment.createdAt).toLocaleString('ar-EG', { timeZone: 'Africa/Cairo', dateStyle: 'medium', timeStyle: 'short' })}</p><div className="mt-3 space-y-1 text-xs font-medium text-[var(--admin-muted)]"><p><span className="font-black text-[var(--admin-text)]">المدرس:</span> {comment.teacherName}</p><p><span className="font-black text-[var(--admin-text)]">الباقة:</span> {comment.packageName}</p><p><span className="font-black text-[var(--admin-text)]">المسار:</span> {comment.termTitle} ← {comment.sectionTitle} ← {comment.lessonTitle}</p></div></div><span className="rounded-lg bg-[var(--admin-card-soft)] px-2.5 py-1 text-xs font-bold">{comment.status === 'Pending' ? 'بانتظار المراجعة' : comment.status === 'Approved' ? 'منشور' : 'مرفوض'}</span></div><p className="mt-4 whitespace-pre-wrap text-sm font-semibold leading-7">{comment.body}</p>{comment.status === 'Pending' && <div className="mt-4 flex gap-2"><button onClick={() => void moderate(comment.id, true)} className="admin-btn-primary inline-flex items-center gap-2"><Check className="h-4 w-4" />نشر</button><button onClick={() => void moderate(comment.id, false)} className="admin-btn-secondary inline-flex items-center gap-2"><X className="h-4 w-4" />رفض</button></div>}</article>)}</div>}</AdminPage>;
}
