namespace NaderGorge.Application.Features.AdminAI.Catalog;

internal static class AdminAIEntityReadSchemas
{
    public const string TeacherSearchOutput = """
        {"type":"object","additionalProperties":false,"properties":{
          "resolution":{"type":"string","enum":["not_found","unique","ambiguous"]},
          "resolvedTeacherId":{"type":"string","format":"uuid"},
          "candidates":{"type":"array","items":{"type":"object","additionalProperties":false,"properties":{
            "teacherId":{"type":"string","format":"uuid"},"displayName":{"type":"string"},
            "specialization":{"type":"string"},"subjectNames":{"type":"array","items":{"type":"string"}},
            "accountActive":{"type":"boolean"}}}},
          "hasMore":{"type":"boolean"}}}
        """;

    public const string StudentSearchOutput = """
        {"type":"object","additionalProperties":false,"properties":{
          "resolution":{"type":"string","enum":["not_found","unique","ambiguous"]},
          "resolvedStudentId":{"type":"string","format":"uuid"},
          "candidates":{"type":"array","items":{"type":"object","additionalProperties":false,"properties":{
            "studentId":{"type":"string","format":"uuid"},"displayName":{"type":"string"},
            "studentCode":{"type":"string"},"phoneEnding":{"type":"string"},
            "educationStage":{"type":"string"},"gradeLevel":{"type":"string"},
            "accountActive":{"type":"boolean"}}}},
          "hasMore":{"type":"boolean"}}}
        """;

    public const string TeacherSubscribersOutput = """
        {"type":"object","additionalProperties":false,"properties":{
          "found":{"type":"boolean"},"teacherId":{"type":"string","format":"uuid"},
          "displayName":{"type":"string"},"packageCount":{"type":"integer"},
          "overall":{"$ref":"#/$defs/scope"},"packageHierarchy":{"$ref":"#/$defs/scope"},
          "directVideo":{"$ref":"#/$defs/scope"},"directExam":{"$ref":"#/$defs/scope"},
          "scopeCountsAreNonAdditive":{"type":"boolean"},
          "unscopedGlobalVideoTypeGrantsExcluded":{"type":"boolean"},"dataAsOf":{"type":"string"}},
         "$defs":{
          "counts":{"type":"object","additionalProperties":false,"properties":{
            "nonGift":{"type":"integer"},"giftOnly":{"type":"integer"},"total":{"type":"integer"}}},
          "scope":{"type":"object","additionalProperties":false,"properties":{
            "active":{"$ref":"#/$defs/counts"},"nonCancelledHistorical":{"$ref":"#/$defs/counts"}}}
         }}
        """;

    public const string StudentSnapshotOutput = """
        {"type":"object","additionalProperties":false,"properties":{
          "found":{"type":"boolean"},"studentId":{"type":"string","format":"uuid"},
          "displayName":{"type":"string"},"phoneEnding":{"type":"string"},
          "includedSections":{"type":"array","items":{"type":"string"}},
          "profile":{"$ref":"#/$defs/profile"},"contact":{"$ref":"#/$defs/contact"},
          "balances":{"$ref":"#/$defs/balances"},"subscriptions":{"$ref":"#/$defs/subscriptions"},
          "activity":{"$ref":"#/$defs/activity"},"assessments":{"$ref":"#/$defs/assessments"},
          "dataAsOf":{"type":"string"}},
         "$defs":{
          "profile":{"type":"object","additionalProperties":false,"properties":{
            "account":{"type":"object","additionalProperties":false,"properties":{
              "studentCode":{"type":"string"},"accountStatus":{"type":"string"},
              "createdAt":{"type":"string"},"isProfileComplete":{"type":"boolean"}}},
            "personal":{"type":"object","additionalProperties":false,"properties":{
              "dateOfBirth":{"type":"string"},"gender":{"type":"string"},"nationality":{"type":"string"}}},
            "academic":{"type":"object","additionalProperties":false,"properties":{
              "educationStage":{"type":"string"},"gradeLevel":{"type":"string"},"studyTrack":{"type":"string"}}},
            "school":{"type":"object","additionalProperties":false,"properties":{
              "schoolName":{"type":"string"},"schoolType":{"type":"string"}}}}},
          "contact":{"type":"object","additionalProperties":false,"properties":{
            "studentPhones":{"type":"object","additionalProperties":false,"properties":{
              "phoneNumber":{"type":"string"},"secondaryPhoneNumber":{"type":"string"}}},
            "guardianPhones":{"type":"object","additionalProperties":false,"properties":{
              "parentPhoneNumber":{"type":"string"},"secondaryParentPhoneNumber":{"type":"string"},
              "motherPhoneNumber":{"type":"string"}}},
            "location":{"type":"object","additionalProperties":false,"properties":{
              "governorate":{"type":"string"},"district":{"type":"string"},"address":{"type":"string"}}}}},
          "balanceTransaction":{"type":"object","additionalProperties":false,"properties":{
            "amountEgp":{"type":"number"},"balanceAfterEgp":{"type":"number"},
            "transactionType":{"type":"string"},"createdAt":{"type":"string"}}},
          "teacherBalance":{"type":"object","additionalProperties":false,"properties":{
            "teacherId":{"type":"string","format":"uuid"},"teacherName":{"type":"string"},
            "availableEgp":{"type":"number"},"nearestExpiryAt":{"type":"string"}}},
          "balances":{"type":"object","additionalProperties":false,"properties":{
            "generalCashEgp":{"type":"number"},"generalPromotionalAvailableEgp":{"type":"number"},
            "teacherScopedBalances":{"type":"array","items":{"$ref":"#/$defs/teacherBalance"}},
            "teacherScopeCount":{"type":"integer"},"contextTeacherId":{"type":"string","format":"uuid"},
            "contextTeacherName":{"type":"string"},"eligiblePromotionalForContextTeacherEgp":{"type":"number"},
            "contextualPurchasingPowerEgp":{"type":"number"},
            "recentGeneralTransactions":{"type":"array","items":{"$ref":"#/$defs/balanceTransaction"}},
            "balanceRuleAr":{"type":"string"}}},
          "grantTypeCount":{"type":"object","additionalProperties":false,"properties":{
            "grantType":{"type":"string"},"count":{"type":"integer"}}},
          "entitlement":{"type":"object","additionalProperties":false,"properties":{
            "grantId":{"type":"string","format":"uuid"},"grantType":{"type":"string"},
            "contentId":{"type":"string","format":"uuid"},"contentName":{"type":"string"},
            "teacherId":{"type":"string","format":"uuid"},"teacherName":{"type":"string"},
            "source":{"type":"string"},"entitlementState":{"type":"string"},
            "isEffective":{"type":"boolean"},"grantedAt":{"type":"string"},
            "expiresAt":{"type":"string"},"cancelledAt":{"type":"string"}}},
          "teacherEntitlement":{"type":"object","additionalProperties":false,"properties":{
            "teacherId":{"type":"string","format":"uuid"},"teacherName":{"type":"string"},
            "hasEffectiveEntitlement":{"type":"boolean"},"effectiveGrantCount":{"type":"integer"},
            "effectiveGrantCountsByType":{"type":"array","items":{"$ref":"#/$defs/grantTypeCount"}}}},
          "subscriptions":{"type":"object","additionalProperties":false,"properties":{
            "totalGrantCount":{"type":"integer"},"activeGrantCount":{"type":"integer"},
            "cancelledGrantCount":{"type":"integer"},"expiredGrantCount":{"type":"integer"},
            "exhaustedGrantCount":{"type":"integer"},"inactiveGrantCount":{"type":"integer"},
            "grantCountsByType":{"type":"array","items":{"$ref":"#/$defs/grantTypeCount"}},
            "recentEntitlements":{"type":"array","items":{"$ref":"#/$defs/entitlement"}},
            "contextTeacherEntitlement":{"$ref":"#/$defs/teacherEntitlement"},
            "teacherScopedBalanceDoesNotGrantAccess":{"type":"boolean"},"accessRuleAr":{"type":"string"}}},
          "watch":{"type":"object","additionalProperties":false,"properties":{
            "videoId":{"type":"string","format":"uuid"},"videoTitle":{"type":"string"},
            "lessonTitle":{"type":"string"},"packageName":{"type":"string"},
            "teacherId":{"type":"string","format":"uuid"},"teacherName":{"type":"string"},
            "watchCount":{"type":"integer"},"isLocked":{"type":"boolean"},"lastWatchedAt":{"type":"string"}}},
          "activity":{"type":"object","additionalProperties":false,"properties":{
            "watching":{"type":"object","additionalProperties":false,"properties":{
              "watchedVideoCount":{"type":"integer"},"totalWatchedSeconds":{"type":"integer"},
              "totalActualWatchedSeconds":{"type":"number"},"lockedVideoCount":{"type":"integer"},
              "lastWatchedAt":{"type":"string"},"recentWatches":{"type":"array","items":{"$ref":"#/$defs/watch"}}}},
            "completedLessonCount":{"type":"integer"},
            "devices":{"type":"object","additionalProperties":false,"properties":{
              "deviceCount":{"type":"integer"},"activeDeviceCount":{"type":"integer"},
              "lastDeviceActiveAt":{"type":"string"}}},
            "commitment":{"type":"object","additionalProperties":false,"properties":{
              "commitmentStatus":{"type":"string"},"consecutiveMissedHomeworks":{"type":"integer"},
              "consecutiveFailedExams":{"type":"integer"}}},
            "warnings":{"type":"object","additionalProperties":false,"properties":{
              "unresolvedWarningCount":{"type":"integer"},"criticalUnresolvedWarningCount":{"type":"integer"}}},
            "adminNotes":{"type":"object","additionalProperties":false,"properties":{
              "adminNoteCount":{"type":"integer"},"pinnedAdminNoteCount":{"type":"integer"}}}}},
          "examAttempt":{"type":"object","additionalProperties":false,"properties":{
            "examId":{"type":"string","format":"uuid"},"examTitle":{"type":"string"},
            "teacherId":{"type":"string","format":"uuid"},"teacherName":{"type":"string"},
            "scoreAchieved":{"type":"number"},"currentTotalScore":{"type":"number"},
            "attemptState":{"type":"string","enum":["in_progress","pending_grading","passed","failed","timed_out"]},
            "attemptedAt":{"type":"string"}}},
          "homeworkItem":{"type":"object","additionalProperties":false,"properties":{
            "homeworkId":{"type":"string","format":"uuid"},"homeworkTitle":{"type":"string"},
            "teacherId":{"type":"string","format":"uuid"},"teacherName":{"type":"string"},
            "scoreAchieved":{"type":"number"},"currentTotalScore":{"type":"number"},
            "status":{"type":"string"},"activityAt":{"type":"string"}}},
          "assessments":{"type":"object","additionalProperties":false,"properties":{
            "exams":{"type":"object","additionalProperties":false,"properties":{
              "examAttemptCount":{"type":"integer"},"distinctExamCount":{"type":"integer"},
              "passedAttemptCount":{"type":"integer"},"failedAttemptCount":{"type":"integer"},
              "inProgressAttemptCount":{"type":"integer"},"pendingGradingAttemptCount":{"type":"integer"},
              "timedOutAttemptCount":{"type":"integer"},"distinctEverPassedExamCount":{"type":"integer"},
              "distinctEverFailedExamCount":{"type":"integer"},
              "recentExamAttempts":{"type":"array","items":{"$ref":"#/$defs/examAttempt"}},
              "passedAndFailedDistinctCountsCanOverlap":{"type":"boolean"},
              "scoresUseCurrentAssessmentTotals":{"type":"boolean"}}},
            "homework":{"type":"object","additionalProperties":false,"properties":{
              "homeworkSubmissionCount":{"type":"integer"},"homeworkGradedCount":{"type":"integer"},
              "homeworkMissedCount":{"type":"integer"},
              "recentHomework":{"type":"array","items":{"$ref":"#/$defs/homeworkItem"}}}},
            "essays":{"type":"object","additionalProperties":false,"properties":{
              "essaySubmissionCount":{"type":"integer"},"essayAwaitingTeacherCount":{"type":"integer"},
              "essayTeacherGradedCount":{"type":"integer"}}}}}
         }}
        """;
}
