name: massar_parent
description: تطبيق مسار أكاديمي لمتابعة ولي الأمر على Android وiOS.
publish_to: none
version: 3.0.0+16
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  flutter_secure_storage: ^11.2.0
  flutter_svg: ^2.3.0
  intl: 0.20.2
  timezone: ^0.11.1
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/onboarding.png
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
