export const queryKeys = {
  session: ['session'] as const,
  employees: {
    all: ['employees'] as const,
    list: (filter = 'all') => ['employees', 'list', filter] as const,
    detail: (id: string) => ['employees', 'detail', id] as const,
  },
  hr: {
    all: ['hr'] as const,
    employees: ['hr', 'employees'] as const,
    organization: ['hr', 'organization'] as const,
    contracts: ['hr', 'contracts'] as const,
    shifts: ['hr', 'shifts'] as const,
    attendance: ['hr', 'attendance'] as const,
    corrections: ['hr', 'corrections'] as const,
    leave: ['hr', 'leave'] as const,
    approvals: ['hr', 'approvals'] as const,
    payroll: ['hr', 'payroll'] as const,
    financialRequests: ['hr', 'financial-requests'] as const,
    documents: ['hr', 'documents'] as const,
    assets: ['hr', 'assets'] as const,
    performance: ['hr', 'performance'] as const,
    cases: ['hr', 'cases'] as const,
    recruitment: ['hr', 'recruitment'] as const,
    lifecycle: ['hr', 'lifecycle'] as const,
    migration: ['hr', 'migration'] as const,
    reports: ['hr', 'reports'] as const,
  },
  content: {
    packages: ['content', 'packages'] as const,
    lessons: (id?: string) => id ? ['content', 'lessons', id] as const : ['content', 'lessons'] as const,
  },
  finance: ['finance'] as const,
  assessments: ['assessments'] as const,
  community: ['community', 'posts'] as const,
  notifications: ['notifications'] as const,
} as const;
